// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOLkNDTYpSFHMI5qzX9CMzuyfBWxpFtzQ',
    appId: '1:464349219629:web:eecd93fb1845b7855921a4',
    messagingSenderId: '464349219629',
    projectId: 'fir-learning-184bb',
    authDomain: 'fir-learning-184bb.firebaseapp.com',
    storageBucket: 'fir-learning-184bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGQSL_SSyJ3HtWgOhT6IcaNiqooY38wOU',
    appId: '1:464349219629:android:30c38cf9d7dfb0405921a4',
    messagingSenderId: '464349219629',
    projectId: 'fir-learning-184bb',
    storageBucket: 'fir-learning-184bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEnCTXul9JYKL9GMiktXXJePfHJmI7KAs',
    appId: '1:464349219629:ios:a9d95ac0c7e17d995921a4',
    messagingSenderId: '464349219629',
    projectId: 'fir-learning-184bb',
    storageBucket: 'fir-learning-184bb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEnCTXul9JYKL9GMiktXXJePfHJmI7KAs',
    appId: '1:464349219629:ios:a9d95ac0c7e17d995921a4',
    messagingSenderId: '464349219629',
    projectId: 'fir-learning-184bb',
    storageBucket: 'fir-learning-184bb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );
}
